"""Top-level service package.

Re-exports the most commonly used service factories for convenience.
"""
from app.services.audit import AuditLogger, get_audit_logger
from app.services.generation import (
    BedrockGenerator,
    GenerationResult,
    Generator,
    RagPipeline,
    StreamingAnswer,
    StubGenerator,
    get_generator,
    get_rag_pipeline,
)
from app.services.ingest import (
    IngestionResult,
    IngestionService,
    OcrResult,
    PassthroughOcrService,
    TextractOcrService,
    get_ingestion_service,
    get_ocr_service,
)
from app.services.pii import (
    ComprehendPiiRedactor,
    PiiRedactionService,
    RegexPiiRedactor,
    get_pii_service,
)
from app.services.rag import (
    BedrockTitanEmbedder,
    Chunk,
    DeterministicHashingEmbedder,
    DocumentChunkUpsert,
    DocumentIndexer,
    Embedder,
    IndexingResult,
    InMemoryVectorStore,
    OpenSearchVectorStore,
    QdrantVectorStore,
    RetrievedChunk,
    Retriever,
    VectorStore,
    chunk_text,
    get_embedder,
    get_indexer,
    get_retriever,
    get_vector_store,
)
from app.services.storage import StorageService, get_storage

__all__ = [
    "AuditLogger",
    "BedrockGenerator",
    "BedrockTitanEmbedder",
    "Chunk",
    "ComprehendPiiRedactor",
    "DeterministicHashingEmbedder",
    "DocumentChunkUpsert",
    "DocumentIndexer",
    "Embedder",
    "GenerationResult",
    "Generator",
    "IndexingResult",
    "InMemoryVectorStore",
    "IngestionResult",
    "IngestionService",
    "OcrResult",
    "OpenSearchVectorStore",
    "PassthroughOcrService",
    "PiiRedactionService",
    "QdrantVectorStore",
    "RegexPiiRedactor",
    "RetrievedChunk",
    "Retriever",
    "StorageService",
    "StreamingAnswer",
    "StubGenerator",
    "TextractOcrService",
    "VectorStore",
    "RagPipeline",
    "chunk_text",
    "get_audit_logger",
    "get_embedder",
    "get_generator",
    "get_indexer",
    "get_ingestion_service",
    "get_ocr_service",
    "get_pii_service",
    "get_rag_pipeline",
    "get_retriever",
    "get_storage",
    "get_vector_store",
]
